### ISSUE TITLE
Pas d'ancrage de rangement des nodes

### ISSUE THREAD

**Issue by alecdek** [rems64/questsEditor#10]
**1.** il faut un ancrage de rangement des nodes.
Sur Scratch ils ont ça. Un quadrillage invisible qui permet de placer les nodes de,façon équilibrée et de pas avoir de trop plein.

Sachant que les structures ont tendance à s'etendre de gauche vers la droite sur le board, tu pourrais meme creer un algorithme constant là dessus, faire en sorte que  lorsque tu ajoute un nouveau node, celui-ci va se ranger tout seul à droite des précédents - et quand tu lies un node B à un node A, le node B va se placer a droite du A.
Si, dans le cadre d'un choix par exemple, tu as deux nodes, B1 et B2, qui suivent le même node A, alors l'algorithme va les équilibret l'un au dessus de l'autre, et le résultat sera propre.

**2.** Des raccourcis clavier. Je veux pas cliquer à chaque fois sur tes boutons en haut de l'interface pour créer de nouveaux nodes. Alors, s'il te plaît mec, Ctrl+J pour nouveau node joueur, Ctrl+P pour PNJ et Ctrl+S pour Switch.
De l'ergonomie, quoi.

**Comment by rems64** [comment]
Ajouté, sauf la disposition automatique à l'ajout d'un nouveau node
