### ISSUE TITLE
Panneau d'options supérieur disparait quand on descend

### ISSUE THREAD

**Issue by alecdek** [rems64/questsEditor#9]
Il faudrait le figer par rapport au reste du board

**Comment by rems64** [comment]
Le problème est-il résolu?

**Comment by rems64** [comment]
@alecdek Dans la v2.1 : rems64/questsEditor/tree/v2.1

**Comment by rems64** [comment]
Solved! 4e7c2e0193ea1d74260db20d4f02907107692ff7
